services:
  frontend-blue:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    networks:
      - app-network
    depends_on:
      - backend-blue
    restart: always

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:4000"
      - "9229:9229" # Port for Node.js debugging
    env_file:
      - .env.production
    volumes:
      - uploads:/app/public/uploads
    restart: always
    networks:
      - app-network
    command: node --inspect=0.0.0.0:9229 /app/server.js # Replace "index.js" with your entry point file

  frontend-green:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8084:3000"
    networks:
      - app-network
    depends_on:
      - backend-green
    restart: always

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:4000"
      - "9230:9229" # Port for Node.js debugging
    env_file:
      - .env.production
    volumes:
      - uploads:/app/public/uploads
    restart: always
    networks:
      - app-network
    command: node --inspect=0.0.0.0:9229 /app/server.js # Replace "index.js" with your entry point file

networks:
  app-network:
    external: true

volumes:
  uploads:
